package org.github.shatterz.sentinelcore.mixin;

import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.text.Text;
import org.github.shatterz.sentinelcore.log.SentinelLogger;
import org.slf4j.Logger;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Ensures the player's display name (used in chat and UI) reflects our custom formatted name
 * generated by NameFormatter.
 */
@Mixin(PlayerEntity.class)
public class PlayerEntityMixin {
  private static final Logger LOG = SentinelLogger.root();

  /** Inject into getDisplayName and override with custom name if present. */
  @Inject(method = "getDisplayName", at = @At("RETURN"), cancellable = true)
  private void injectCustomDisplayName(CallbackInfoReturnable<Text> cir) {
    PlayerEntity player = (PlayerEntity) (Object) this;
    Text customName = player.getCustomName();
    if (customName != null) {
      LOG.info(
          "[Mixin] getDisplayName override for {} -> {}",
          player.getName().getString(),
          customName.getString());
      cir.setReturnValue(customName);
    }
  }
}
