name: Build & Smoke (Temurin 21)

on:
  push:
    branches: [ "dev", "feature/**" ]
  pull_request:
    branches: [ "dev", "feature/**" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Gradle build on Windows (Temurin 21)
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Spotless (format)
        run: .\gradlew.bat --no-daemon :spotlessApply

      - name: Build
        run: .\gradlew.bat --no-daemon build

      - name: Prep run directory (EULA + server.properties)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path ".\run" | Out-Null
          # Accept EULA so server can start
          Set-Content -NoNewline -Path ".\run\eula.txt" -Value "eula=true`r`n"
          # Minimal server.properties (CI-friendly)
          @"
#Minecraft server properties
  motd=SentinelCore CI Smoke
  server-port=25565
  rcon.port=25575
  enable-rcon=false
  max-players=1
  online-mode=false
  enable-command-block=false
  difficulty=easy
  gamemode=survival
  "@ | Set-Content -Path ".\run\server.properties" -NoNewline

      - name: Server smoke test (150s)
        continue-on-error: true   # ← add this line temporarily
        shell: pwsh
        run: |
          $p = Start-Process -FilePath ".\gradlew.bat" -ArgumentList "--no-daemon runServer" -PassThru -WindowStyle Hidden
          Start-Sleep -Seconds 150
          if (-not $p.HasExited) { Stop-Process -Id $p.Id -Force }
          $logPath = ".\run\logs\latest.log"
          if (-not (Test-Path $logPath)) { Write-Host "❌ No server log"; exit 1 }
          $log = Get-Content $logPath -Raw
          if ($log -match "Done \(" -or $log -match "Starting minecraft server") { exit 0 }
          Write-Host "❌ Smoke failed. Tail:"; Get-Content $logPath | Select-Object -Last 200; exit 1




      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SentinelCore-${{ github.ref_name }}-${{ github.sha }}
          path: build/libs/*.jar
          if-no-files-found: error
