name: Build (Temurin 21)

on:
  push:
    branches:
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - dev
      - 'feature/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Gradle version
        run: .\gradlew.bat --version